#!/usr/bin/env bash

# Copyright (c) 2021-2026 community-scripts ORG
# Author: Arm (Sub-Creator)
# License: MIT | https://github.com/community-scripts/ProxmoxVED/raw/main/LICENSE
# Source: https://github.com/3proxy/3proxy

source /dev/stdin <<<"$FUNCTIONS_FILE_PATH"
color
verb_ip6
catch_errors
setting_up_container
network_check
update_os

# ------------------------------------------------------------------------------
# 3proxy - Tiny free proxy server
#
# Supports 14+ proxy services via single binary set:
#   proxy  (HTTP CONNECT), socks (SOCKS5), socks4, pop3p, smtpp,
#   ftppr, dnspr, tcppm, udppm, tlspr
#
# Default listening ports (override via PROXY_HTTP_PORT / PROXY_SOCKS_PORT, etc.):
#   3128  HTTP proxy
#   1080  SOCKS5
#   1081  SOCKS4
#   1100  POP3 proxy
#   8025  SMTP proxy
#   2121  FTP proxy
#   5353  DNS proxy
# ------------------------------------------------------------------------------

msg_info "Installing Dependencies"
$STD apt install -y openssl ca-certificates
msg_ok "Installed Dependencies"

# ------------------------------------------------------------------------------
# 1. Install 3proxy from official .deb release
# ------------------------------------------------------------------------------
msg_info "Installing 3proxy (GitHub release)"

RELEASE=$(get_latest_github_release "3proxy/3proxy")
ARCH=$(dpkg --print-architecture)
case "$ARCH" in
  amd64) DEB_FILE="3proxy-${RELEASE}.x86_64.deb" ;;
  arm64) DEB_FILE="3proxy-${RELEASE}.arm64.deb" ;;
  armhf) DEB_FILE="3proxy-${RELEASE}.arm.deb"   ;;
  *)
    msg_error "Unsupported architecture: $ARCH"
    exit 1
    ;;
esac

DEB_URL="https://github.com/3proxy/3proxy/releases/download/${RELEASE}/${DEB_FILE}"
curl -fsSL -o /tmp/3proxy.deb "$DEB_URL"
$STD dpkg -i /tmp/3proxy.deb
rm -f /tmp/3proxy.deb
msg_ok "Installed 3proxy ${RELEASE}"

# ------------------------------------------------------------------------------
# 2. Generate random credentials (16-char alphanumeric)
# ------------------------------------------------------------------------------
msg_info "Generating Proxy Credentials"

PROXY_USER=$(prompt_input "Proxy username" "proxyuser" 30)
PROXY_PASS=$(prompt_password "Proxy password" "generate" 30 8)
PROXY_PASS_HASH=$(/usr/bin/mycrypt 12345 "$PROXY_PASS")
PROXY_PASS_HASH="${PROXY_PASS_HASH#CR:}" # strip CR: prefix for passwd file format

# Save credentials to /root/3proxy.creds (chmod 600)
cat > /root/3proxy.creds <<CREDSEOF
# 3proxy Credentials
# Generated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')
# IP: ${IP:-<container-ip>}
# Username: ${PROXY_USER}
# Password: ${PROXY_PASS}
# Hash (CR): ${PROXY_PASS_HASH}
CREDSEOF
chmod 600 /root/3proxy.creds
msg_ok "Generated Proxy Credentials (saved to /root/3proxy.creds)"

# ------------------------------------------------------------------------------
# 3. Build /etc/3proxy/3proxy.cfg
#
# Service selection — defaults: HTTP CONNECT + SOCKS5 + SOCKS4 + POP3 + SMTP + FTP
# All services share the same single user account (PROXY_USER).
# ------------------------------------------------------------------------------
msg_info "Writing /etc/3proxy/3proxy.cfg"

# External passwd file (avoids $1$ being parsed as 3proxy variable inline)
mkdir -p /etc/3proxy/conf
printf 'users %s:CR:%s\n' "$PROXY_USER" "$PROXY_PASS_HASH" > /etc/3proxy/conf/passwd
chmod 600 /etc/3proxy/conf/passwd

cat > /etc/3proxy/3proxy.cfg <<CFGEOF
#!/usr/bin/3proxy

# 3proxy configuration
# Generated by Proxmox community-scripts/3proxy
# Edit /etc/3proxy/3proxy.cfg to customise. Reload: systemctl reload 3proxy

daemon
pidfile /run/3proxy/3proxy.pid
nserver 1.1.1.1
nserver 8.8.8.8
nscache 65536

# --- Listener 1: HTTP CONNECT + SOCKS5 + SOCKS4 ---
flush
auth strong
users \$/etc/3proxy/conf/passwd
allow ${PROXY_USER}
proxy -p${PROXY_HTTP_PORT:-3128} -n
socks -p${PROXY_SOCKS_PORT:-1080}
socks -p${PROXY_SOCKS4_PORT:-1081} -4
flush

# --- Listener 2: Mail (POP3 / SMTP) + FTP ---
flush
auth strong
users \$/etc/3proxy/conf/passwd
allow ${PROXY_USER}
pop3p -p${PROXY_POP3_PORT:-1100}
smtpp -p${PROXY_SMTP_PORT:-8025}
ftppr -p${PROXY_FTP_PORT:-2121}
flush
CFGEOF

chmod 644 /etc/3proxy/3proxy.cfg
msg_ok "Wrote /etc/3proxy/3proxy.cfg"

# ------------------------------------------------------------------------------
# 4. Logging directory (3proxy logs to stdout by default; this is for audit logs)
# ------------------------------------------------------------------------------
mkdir -p /var/log/3proxy
chown proxy:proxy /var/log/3proxy
chmod 0755 /var/log/3proxy

# ------------------------------------------------------------------------------
# 5. Enable + start systemd service (provided by .deb)
# ------------------------------------------------------------------------------
msg_info "Starting 3proxy Service"
systemctl enable -q --now 3proxy
sleep 1
if systemctl is-active --quiet 3proxy; then
  msg_ok "3proxy Service Active"
else
  msg_error "3proxy Service failed to start"
  $STD journalctl -u 3proxy --no-pager -n 20
  exit 1
fi

motd_ssh
customize
cleanup_lxc
